const assert = require('node:assert/strict');
const model = require('../codenotch/ui/model.js');
const primary = { id: 'primary', label: '5h limit', used: .8, resets_at: 2000000 };
const weekly = { id: 'secondary', label: 'Weekly limit', used: .06, resets_at: 3000000 };
const snap = { status: 'ok', fetched_at: 1000000, windows: [primary, weekly] };
assert.equal(model.headline(snap, 'weekly'), weekly);
assert.equal(model.headline(snap, 'highest'), primary);
assert.equal(model.headline({windows:[{...weekly,id:'primary'}]}, 'weekly').used, .06);
assert.equal(model.headline({windows:[primary]}, 'weekly'), primary);
assert.equal(model.headline({windows:[]}), null);
assert.equal(model.headline({windows:[{used:0,label:'Weekly limit'}]},'weekly').used,0);
assert.equal(model.stale(snap, 1100000), false);
assert.equal(model.stale(snap, 1400000), true);
assert.equal(model.stale({...snap,status:'needsAuth'}, 1100000), true);
assert.equal(model.stale({...snap,windows:[{...primary,resets_at:1000000}]}, 1100000), true);
assert.equal(model.percent(.06),6);assert.equal(model.percent(1.1),100);assert.equal(model.percent(-1),0);
assert.equal(model.escape('<script>"&'), '&lt;script&gt;&quot;&amp;');
assert.equal(model.clamp(50,8,-20),8);
console.log('Presentation checks passed: window selection, missing data, freshness, bounds and escaping.');
